<!DOCTYPE>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
<title>{{ $config['SITE_NAME'] }}</title>
<link rel="shortcut icon" type="image/png" href="/favicon.png" />
<link media="all" rel="stylesheet" type="text/css" href="/assets/css/global.css?v=<?php echo time(); ?>" />
<script src='/assets/js/jquery-3.3.1.min.js' type='text/javascript'></script>
</head>

<body>
<a id="logo" href="/"></a>
<div id="content">
<h1>{{ $config['SITE_NAME'] }}</h1>